apiVersion: v1
kind: Service
metadata:
  name: platform
  namespace: sentinelscale
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/part-of: sentinelscale
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform
  ports:
    - name: http
      port: 8003
      targetPort: 8003
