apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sentinelscale
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/part-of: sentinelscale
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s

    scrape_configs:
      - job_name: 'sentinelscale-services'
        metrics_path: '/metrics'
        static_configs:
          - targets:
              - 'demo-api.sentinelscale.svc.cluster.local:8000'
              - 'platform.sentinelscale.svc.cluster.local:8003'
            labels:
              environment: 'production'
              cluster: 'sentinelscale-k8s'
