apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: sentinelscale
  labels:
    app.kubernetes.io/name: demo-api
    app.kubernetes.io/part-of: sentinelscale
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
