apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"(?:otel_trace_id|trace_id)":\s*"([a-f0-9]{32})"'
          url: '$${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: 'View Tempo Trace'
