from pydantic import BaseModel, Field


class ResourceState(BaseModel):
    event_id: str = Field(..., description="Unique snapshot UUID.")
    trace_id: str = Field(..., description="Distributed tracing identifier.")
    timestamp: str = Field(..., description="ISO-8601 observation timestamp.")
    contract_version: str = Field(..., pattern=r"^[0-9]+\.[0-9]+\.[0-9]+$", description="Contract version.")
    service_version: str = Field(..., description="Platform service version.")
    target_namespace: str = Field(..., description="Target namespace.")
    target_workload: str = Field(..., description="Target workload/deployment name.")
    cpu_utilization: float = Field(..., ge=0.0, description="Average CPU utilization ratio.")
    memory_utilization: float = Field(..., ge=0.0, description="Average Memory utilization ratio.")
    cpu_requested_cores: float = Field(..., ge=0.0, description="Total requested CPU cores.")
    cpu_limit_cores: float = Field(..., ge=0.0, description="Total CPU limit cores.")
    memory_requested_bytes: int = Field(..., ge=0, description="Total requested memory in bytes.")
    memory_limit_bytes: int = Field(..., ge=0, description="Total memory limit in bytes.")
    running_pods: int = Field(..., ge=0, description="Count of running pods.")
    desired_pods: int = Field(..., ge=0, description="Count of desired pods.")
    pending_pods: int = Field(..., ge=0, description="Count of pending pods.")
    request_rate: float = Field(..., ge=0.0, description="Aggregate observed RPS.")
    p95_latency_ms: float = Field(..., ge=0.0, description="P95 latency in ms.")
    error_rate: float = Field(..., ge=0.0, le=1.0, description="HTTP 5xx error rate ratio.")
    current_capacity_rps: float = Field(..., ge=0.0, description="Current total processing capacity (RPS).")
    estimated_required_capacity_rps: float = Field(..., ge=0.0, description="Estimated capacity (RPS) needed.")
    estimated_resource_waste: float = Field(..., ge=0.0, le=1.0, description="Estimated overprovisioned waste ratio.")
